[package]
name = "blzrd"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0"
authors = ["Aly Raffauf <aly@aly.codes>"]

[[bin]]
name = "blzrd"
path = "src/main.rs"

[dependencies]
tokio = { version = "1", features = [
    "rt-multi-thread",
    "macros",
    "process",
    "time",
] }
clap = { version = "4", features = ["derive", "env"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
anyhow = "1"
futures = "0.3"
log = "0.4"
env_logger = "0.11"
openssh = "0.11"
uuid = { version = "1", features = ["v4"] }
